name: Build PerfectPlacement

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        rimworld_version: [ '1.4', '1.5', '1.6' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore packages
      run: dotnet restore Source/PerfectPlacement.csproj -p:GameVersion=${{ matrix.rimworld_version }}

    - name: Build for RimWorld ${{ matrix.rimworld_version }}
      run: dotnet build Source/PerfectPlacement.csproj -c Release -p:GameVersion=${{ matrix.rimworld_version }} --no-restore

    - name: Package mod for ${{ matrix.rimworld_version }}
      shell: pwsh
      run: |
        $ErrorActionPreference = 'Stop'
        $version = '${{ matrix.rimworld_version }}'
        $pkgRoot = Join-Path $PWD "package"
        New-Item -ItemType Directory -Force -Path $pkgRoot | Out-Null
        $staging = Join-Path $pkgRoot "PerfectPlacement-$version"
        if (Test-Path $staging) { Remove-Item -Recurse -Force $staging }
        New-Item -ItemType Directory -Force -Path $staging | Out-Null
        # Copy common mod content
        Copy-Item -Recurse -Force About (Join-Path $staging 'About')
        if (Test-Path 'Defs') { Copy-Item -Recurse -Force Defs (Join-Path $staging 'Defs') }
        # Copy version-specific assemblies
        Copy-Item -Recurse -Force $version (Join-Path $staging $version)
        # Optional: include license/readme
        if (Test-Path 'LICENSE') { Copy-Item -Force LICENSE (Join-Path $staging 'LICENSE') }
        if (Test-Path 'README.md') { Copy-Item -Force README.md (Join-Path $staging 'README.md') }
        # Create zip
        $zipPath = Join-Path $pkgRoot ("PerfectPlacement-$version.zip")
        if (Test-Path $zipPath) { Remove-Item -Force $zipPath }
        Compress-Archive -Path (Join-Path $staging '*') -DestinationPath $zipPath

    - name: Upload artifact for ${{ matrix.rimworld_version }}
      uses: actions/upload-artifact@v4
      with:
        name: PerfectPlacement-${{ matrix.rimworld_version }}
        path: package/PerfectPlacement-${{ matrix.rimworld_version }}.zip

  release:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: PerfectPlacement-*
          merge-multiple: true

      - name: Compute next tag
        id: compute_tag
        shell: bash
        run: |
          set -euo pipefail
          git fetch --tags --force
          latest=$(git tag -l 'v*' | sort -V | tail -n 1)
          if [ -z "$latest" ]; then
            new="v1.0.0"
          else
            base=${latest#v}
            IFS='.' read -r major minor patch <<< "$base"
            patch=${patch:-0}
            patch=$((patch+1))
            new="v${major}.${minor}.${patch}"
          fi
          echo "tag=$new" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.compute_tag.outputs.tag }}
          target_commitish: ${{ github.sha }}
          name: PerfectPlacement ${{ steps.compute_tag.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            PerfectPlacement-*.zip
