name: Build PerfectPlacement

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        # Add the RimWorld versions you want to build for
        rimworld_version: [ '1.4', '1.5', '1.6' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Download RimWorld Assemblies for ${{ matrix.rimworld_version }}
      run: |
        $url = "https://github.com/pardeike/RimWorld-Assemblies/raw/master/${{ matrix.rimworld_version }}/Assemblies.zip"
        $output = "Assemblies.zip"
        Invoke-WebRequest -Uri $url -OutFile $output
        Expand-Archive -Path $output -DestinationPath "Source/packages/Assemblies/"
      shell: pwsh

    - name: Build for RimWorld ${{ matrix.rimworld_version }}
      run: |
        msbuild Source/PerfectPlacement.csproj /p:Configuration=Release /p:Platform=AnyCPU /p:GameVersion=${{ matrix.rimworld_version }} /p:ReferencePath="Source/packages/Assemblies/"
      
    - name: Upload Artifact for ${{ matrix.rimworld_version }}
      uses: actions/upload-artifact@v3
      with:
        name: PerfectPlacement-${{ matrix.rimworld_version }}
        path: Source/bin/Release/PerfectPlacement.dll
